#!/usr/bin/env bash
# Script that transfers a file from our client to a server
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	file_path=$1
	ip_addr=$2
	username=$3
	key_path=$4

	scp -o StrictHostKeyChecking=no -i "$key_path" "$file_path" "$username"@"$ip_addr":~/
fi
