#!/usr/bin/env bash
# Install nginx on your web server
# Nginx should be listening on port 80

apt-get -y update
apt-get -y install nginx
cp /var/www/html/index.nginx-debian.html /var/www/html/index_bckup
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx restart
