#!/usr/bin/env bash
# Install nginx on your web server
# Nginx should be listening on port 80

apt-get -y update
apt-get -y install nginx
cp /var/www/html/index.nginx-debian.html /var/www/html/index_bckup
echo "Hello World!" > /var/www/html/index.nginx-debian.html
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default_backup
tee /etc/nginx/sites-available/default <<EOF
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location /redirect_me {
		return 301 https://www.google.com;
	}
}
EOF
service nginx restart
