#!/usr/bin/env bash
# Install nginx on your web server
# Nginx should be listening on port 80

apt-get -y update
apt-get -y install nginx
HOSTNAME=$(hostname)
cp /var/www/html/index.nginx-debian.html /var/www/html/index_bckup
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
cp -n /etc/nginx/sites-available/default /etc/nginx/sites-available/default_backup
tee /etc/nginx/sites-available/default <<EOF
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location /redirect_me {
		return 301 https://www.google.com;
	}

	error_page 404 /404.html;
	location /404 {
		root /var/www/html;
		internal;
	}

	# Add custom header
	add_header X-Served-By $HOSTNAME;
}
EOF
service nginx restart
